### PR TITLE
add missing dep, fix volume name

### PR DESCRIPTION
**Pull request by blackpr**
- fixed docker volume names
- added the missing `connect-pg-simple` dependency

### CODE REVIEW

**Comment by TheJoeSchr** [comment]
Hi @blackpr and thanks for your help!

Sadly I missed your PR at the time and since then @benjie work on https://github.com/graphile/bootstrap-react-apollo/commit/eb90c01dc5a9c6297918fb59a50a0a6a573db307 https://github.com/graphile/bootstrap-react-apollo/commit/36d06ba04c66878bf649bf234001f8ffb446d49c which I just merged from upstream also incorporated your changes (with an even newer version)

Next time I will try to react sooner, please keep improving our project!
Thanks

**Comment by TheJoeSchr** [comment]
I also messed up by deleting `yarn.lock` from your commit. But I just merged your permission changes on `wait-for.sh` to 0755. Thanks for that

**Comment by TheJoeSchr** [comment]
But now it's not attributed to you! I'm very sorry about that, but I don't know how to fix it

**Comment by blackpr** [comment]
No worries. Its fine :)

**Comment by TheJoeSchr** [comment]
Ah, disregard. It's in the history, just so far back that I didn't see it.

**Pull request closed without merging**
